### ISSUE TITLE
Why are these awesome?

### ISSUE THREAD

**Issue by RichardLitt** [devspace/awesome-github-templates#3]
I'm not sure what makes any of the items here awesome. What is an awesome github issue template?

**Comment by zenorocha** [comment]
You know the answer already.

Why is isobar on awesome-styleguides? Why is The Silmarillion by J.R.R. Tolkien on awesome-fantasy? Why is BrooklynJS on awesome-conferences?

They are there because you found it better than other things. They have something different that others don't have. 

An awesome issue template is a piece of content that informs contributors how to proceed in a very detailed or unique way.

**Comment by RichardLitt** [comment]
Heh. That is a fair point. I need to get around to maintaining those a bit better.

I ask because this list is fairly new, and I wanted to know if you've turned down other templates that currently exist. I'm guessing there is going to be a lot of churn in how these templates look over the next few months, so I was wondering what you considered awesome, right now.
